sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t nsd96/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true nsd96/docker-react-app npm run test -- 

after_success:
  - echo "Test success"

